### ISSUE TITLE
Redundant use of public in generated default instances.

### ISSUE THREAD

**Issue by kyleishie** [amzn/service-model-swift-code-generate#4]
When generating default structure instances the _public_ modifier is used redundantly in that it is on both the generated extension and the generated static method.  This causes compiler warnings in the generated project for each model.  

I recommend removing _public_ from the generated static method.  I can submit a PR for this change but I wanted to discuss it here first.

**Comment by tachyonics** [comment]
Thanks for raising this Kyle!

This is a change from Swift 4.2 to Swift 5.x. Removing the public modifier would not be compatible with Swift versions prior to 5.0. It might be worth thinking about some kind of input specifying compatibility for the code that is generated. Thoughts?

**Comment by kyleishie** [comment]
After posting this issue I realized that this is a swift 5.x warning and therefore something that should be fixed when updating the package(s) to Swift 5.x.  It's probably not worth the time to implement a compatibility argument in that case.  Any idea when this update is expected?  I would be happy to help. 😁

**Comment by tachyonics** [comment]
I have started doing some initial work for this here-

* https://github.com/amzn/service-model-swift-code-generate/tree/swift_5_nio_2
* https://github.com/amzn/smoke-aws-generate/tree/swift_5_nio_2

Which will generate-
* https://github.com/amzn/smoke-aws/tree/swift_5_nio_2

I need to write a vision doc for the changes we'd like to include in the next version of all these repositories but once we have this doc, if you'd like to take over these changes and make sure everything is included in the generator, that would be great!

**Comment by kyleishie** [comment]
Sorry for the delayed response.  I have been grinding on various new web services at work.  And yes they are smoke based. 😎

I will take a look at what you have done so far over the next week or two as I have time.  In the mean time, I will join glitter so we can discuss the vision of this and the other repos.  I really enjoy using the smoke framework and want to be apart of making it the goto in our community.

**Comment by tachyonics** [comment]
Hi Kyle, sorry for never responding on this; last year was very busy and I must have missed your message. This issue has been fixed for version 2.0.0 which is being released. I will resolve this. Let us know if you have any other issues.
